name: Deploy to AWS

run-name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "ap-southeast-1"
  ASG_NAME: flask-app
  DOCKER_HUB_REPO: integrity11/my_blog_app
  LAUNCH_TEMPLATE: web_app 
  TAG: latest


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB  }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB }}/my_blog_app:latest

  deploy:
    name: Deploy 
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3  

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2     # default
          verbose: false # default
          arch: amd64    # allowed values: amd64, arm64
    
      - name: Update Auto Scaling Group with Launch Template
        run: |
          echo "---- BEGIN SCALING ---------"
          echo "ASG_NAME = "flask-app" "
          echo "DOCKER_HUB_REPO = "integrity11/my_blog_app" "
          echo "LAUNCH_TEMPLATE = "web_app" " 
          echo "TAG = "latest" "
          # Create a new version of the Launch Template with the updated image
          NEW_LAUNCH_TEMPLATE=$(aws ec2 create-launch-template-version \
            --launch-template-name LAUNCH_TEMPLATE \
            --source-version 1 \
            --user-data user_data_script.txt
            --query "LaunchTemplateVersion.VersionNumber" --output text)

          # Update the ASG to use the new Launch Template version
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name $ASG_NAME \
            --launch-template "LaunchTemplateName=$LAUNCH_TEMPLATE,Version=$NEW_LAUNCH_TEMPLATE_VERSION"
  


      